### ISSUE TITLE
[Proposal] Let the user relaunch "deep" wallet restoration from Settings page

### ISSUE THREAD

**Issue by louisinger** [TDex-network/tdex-app#181]
ATM each time the user login, we restore its wallet (i.e addresses) from localStorage + EsploraRestorer. The Esplora's restorer checks if the next address has transactions and stops if there is a set of **20** addresses without any transactions. 

In some cases, this can be a problem. For example, if the wallet is composed of a sequence of 20 unused addresses -> the next one will be "unknown" by the app. if this address has been used, the user won't see the associated utxos or transactions.

We could add a way (through the Settings screen for instance) to recover "deeply" the user's wallet. i.e increase the restoration bound and then restore the wallet.

**Comment by Janaka-Steph** [comment]
What about using the slider component here? Could be with 3 steps (soft: 50 addresses, medium: 100 addresses, aggressive: 200 addresses), or without steps but min-max bounds.
Theoretically user could need more than 200 gap limit, but should not happen in real life.

**Comment by tiero** [comment]
In Marina we added indeed a select box, with 20,40,60,80 if I remember correctly, so slider works for me
