### ISSUE TITLE
[Android] App icon is not sized properly

### ISSUE THREAD

**Issue by Janaka-Steph** [TDex-network/tdex-app#280]
![logo](https://user-images.githubusercontent.com/4022128/120534091-5a958500-c3d9-11eb-8dfe-1212f2bc6fd3.jpg)

**Comment by tiero** [comment]
Hey @FilippoSeven  Can you provider the icon in SVG format? thanks

**Comment by tiero** [comment]
[TDex_Android_Icon.zip](https://github.com/TDex-network/tdex-app/files/6724515/TDex_Android_Icon.zip)

**Comment by Janaka-Steph** [comment]
This svg will not work. I need the logo to be 66% of the current size. Or the background to be wider. If @FilippoSeven can provide the green logo and the background separately I can make the icon myself.

**Comment by FilippoSeven** [comment]
[TDex_LOGO_Icon.zip](https://github.com/TDex-network/tdex-app/files/6725048/TDex_LOGO_Icon.zip)
 Here 2 SVGs
