### ISSUE TITLE
Self-transfer withdrawal: "no blind key" error

### ISSUE THREAD

**Issue by louisinger** [TDex-network/tdex-app#299]
self-transfer withdrawal (i.e generate a new address and then send it some funds) fails with `no blind key error`. 

Probably because we **do not** persist the generated addresses via "deposit" until we find an utxo (see `watchUtxo` saga). That's why the blindKeyGetter can't find the blinding public key while we try to send funds to a wallet's address. 

FIX proposal: Either we persist the generated address (even if we do not receive funds on it) or we should handle the self-transfer case inside the blindKeyGetter.

**Comment by tiero** [comment]
What about this? @louisinger @Janaka-Steph

**Comment by tiero** [comment]
cc/ @louisinger

**Comment by louisinger** [comment]
it seems to be solved
