### ISSUE TITLE
If user deletes all the digits in exchnage row, do not replace with 0, but leave the placehoder empty

### ISSUE THREAD

**Issue by tiero** [TDex-network/tdex-app#318]

**Comment by Janaka-Steph** [comment]
Not even greyed zero?

**Comment by tiero** [comment]
placehoder I mean the greyed zero yes (the You send row)
![image](https://user-images.githubusercontent.com/3596602/123242743-9f956e80-d4e2-11eb-9ccb-53f402da22bf.png)
