### ISSUE TITLE
Cannot withdraw to Green generated address

### ISSUE THREAD

**Issue by altafan** [tdex-network/tdex-app#433]
I'm trying to withdraw my funds from the app to an address generated with Green like this one `VJL9czxRqdrQ4MP4m1KRXx7DtJTT9Givp4sTYi7q7LKTiXyaN4jnYsbHHTrx3MxzYt7Lf9xHMyBP1HjD`.
It seems that the address is not recognized as valid from the app and I cannot tap on the `Confirm` button.

**Comment by tiero** [comment]
You are missing the input with the amount? :hugs:

**Comment by tiero** [comment]
![image](https://user-images.githubusercontent.com/3596602/132853324-8aa7c33e-7c6d-4da0-94fd-5ec93c1260f2.png)
