### ISSUE TITLE
Handle provider's ProposeTrade Unknown errors and/or SwapFail showing the explicit error and suggesting to either retry or try the next provider in the queue

### ISSUE THREAD

**Issue by tiero** [tdex-network/tdex-app#443]
When a `SwapFail` or  an UNKNOWN error is returned by the provider on {Propose/Complete}Trade instead of a generic error toast, we should do the following:

open a bigger dialog/modal where we show the full explicit SwapFail failure message (or Error catched) returned by the provider and adding call to actions such as "Hey please retry" and "If try again does not solves, uses another provider, this one next in the list is available"

**Comment by altafan** [comment]
cc @louisinger

**Comment by louisinger** [comment]
> open a bigger dialog/modal where we show the full explicit SwapFail failure message (or Error watched) 

I think we should enrich the Errors thrown by `buy` and `sell` methods in tdex-sdk. At least to know which request has failed (tradePropose, proposeTrade, tradeComplete etc...)
