### ISSUE TITLE
Update to CRA 5

### ISSUE THREAD

**Issue by Janaka-Steph** [tdex-network/tdex-app#530]
CreateReactScript 5 switched from webpack 4 to webpack 5, which removed NodeJS polyfills.
Can't resolve 'crypto', 'path', 'stream', 'fs', 'util', 'os'.

We would need to eject from CRA and add the polyfills, use solution like Craco, or just stay on CRA 4.

List of polyfills: https://github.com/webpack/node-libs-browser

**Comment by tiero** [comment]
This should work https://www.npmjs.com/package/node-polyfill-webpack-plugin

Used here https://github.com/tiero/pegin-marina/blob/master/webpack.config.js#L71

**Comment by Janaka-Steph** [comment]
The thing is that we didn't eject CRA or use craco in this project. Do we really want to do it? Also still need to figure out how to do it in Ionic.

**Comment by Janaka-Steph** [comment]
If we choose to polyfill I think we can just add what we are missing, not all of them as in [node-polyfill-webpack-plugin](https://www.npmjs.com/package/node-polyfill-webpack-plugin)

**Comment by tiero** [comment]
> The thing is that we didn't eject CRA or use craco in this project. Do we really want to do it? Also still need to figure out how to do it in Ionic.

So it should be done in out react-scripts fork then?

**Comment by Janaka-Steph** [comment]
Yes I forgot we are forking CRA so yes we could modify webpack there
