### ISSUE TITLE
Black screen after entering wallet pin on login

### ISSUE THREAD

**Issue by blankscreengithub** [tdex-network/tdex-app#577]
![Screenshot_20221227_081709_TDEX](https://user-images.githubusercontent.com/66571264/209679832-193654a0-b91b-46f1-bf10-51ed380db2b8.jpg)

I get a blank screen after entering my pin when opening the app.

Samsung S21
Android 13

**Comment by Janaka-Steph** [comment]
Hello @blankscreengithub,
Can you tell me the version of your app please? 
Did you try to reinstall it?

**Comment by blankscreengithub** [comment]
Version is 1.2.7.

Uninstalling the app and reinstalling and restoring my wallet fixed the problem.

**Comment by Janaka-Steph** [comment]
Ok good, sorry for the inconvenience.
