### ISSUE TITLE
[v2] Fix suggested words when typing mnemonic

### ISSUE THREAD

**Issue by altafan** [tdex-network/tdex-app#594]
When I type the words of my mnemonic (restore flow), if I select the suggested word of my keyboard, the very first word of the mnemonic is overwritten while the second is deleted, while the current is not changed at all as you can see in the image below (I selected "devote"):

<img src="https://github.com/tdex-network/tdex-app/assets/18440657/93e8a057-269d-40b9-83c7-efda576aa433" width="300" />

**Comment by Janaka-Steph** [comment]
Fixed on v2
