### ISSUE TITLE
Have to guess fee on android app

### ISSUE THREAD

**Issue by GlytchMeister** [tdex-network/tdex-app#600]
Sending L-BTC from TDEX has lost me at least a few bucks in fees from having to get refunds because 90% of the time, the fee applied by the app cuts the amount I actually send below what the receiving service is requesting.  There is no way for me to see what the fee is going to be until after I hit Confirm, so I have been trying to guess, and because the fees are fluctuating and also seem to be expressed in sats and not in BTC, I'm stuck trying to count decimal places and trying to thread the needle between sending too much and not enough.

Please either take fees out of the remaining balance or show what the fee is gonna be instead of taking it out of the amount being sent, this is infuriating

**Comment by tiero** [comment]
TDEX app has a send all feature! Clicking on the balance in the send screen, will fill all the amount in the input and deduct fees. You don't need to do math
